//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
