//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMedia
    {
        public int ProductMediaId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Photo { get; set; }
        public string Video { get; set; }
    }
}
